/*
 * Copyright (c) 2025, MediaTek Inc. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef APUSYS_CE_H
#define APUSYS_CE_H

#include <platform_def.h>


#define APU_ACE_SW_REQ_0			(APU_ARE_REG_BASE + 0x400)
#define APU_ACE_SW_REQ_1			(APU_ARE_REG_BASE + 0x404)
#define APU_ACE_SW_REQ_2			(APU_ARE_REG_BASE + 0x408)
#define APU_ACE_SW_REQ_3			(APU_ARE_REG_BASE + 0x40c)
#define APU_ACE_SW_REQ_4			(APU_ARE_REG_BASE + 0x410)
#define APU_ACE_SW_REQ_5			(APU_ARE_REG_BASE + 0x414)
#define APU_ACE_SW_REQ_6			(APU_ARE_REG_BASE + 0x418)
#define APU_ACE_SW_REQ_7			(APU_ARE_REG_BASE + 0x41c)
#define APU_ACE_SW_REQ_0_USER			(APU_ARE_REG_BASE + 0x420)
#define APU_ACE_SW_REQ_1_USER			(APU_ARE_REG_BASE + 0x424)
#define APU_ACE_SW_REQ_2_USER			(APU_ARE_REG_BASE + 0x428)
#define APU_ACE_SW_REQ_3_USER			(APU_ARE_REG_BASE + 0x42c)
#define APU_ACE_SW_REQ_4_USER			(APU_ARE_REG_BASE + 0x430)
#define APU_ACE_SW_REQ_5_USER			(APU_ARE_REG_BASE + 0x434)
#define APU_ACE_SW_REQ_6_USER			(APU_ARE_REG_BASE + 0x438)
#define APU_ACE_SW_REQ_7_USER			(APU_ARE_REG_BASE + 0x43c)
#define APU_ACE_CMD_Q_STATUS_0			(APU_ARE_REG_BASE + 0x440)
#define APU_ACE_CMD_Q_STATUS_1			(APU_ARE_REG_BASE + 0x444)
#define APU_ACE_CMD_Q_STATUS_2			(APU_ARE_REG_BASE + 0x448)
#define APU_ACE_CMD_Q_STATUS_3			(APU_ARE_REG_BASE + 0x44c)
#define APU_ACE_CMD_Q_STATUS_4			(APU_ARE_REG_BASE + 0x450)
#define APU_ACE_CMD_Q_STATUS_5			(APU_ARE_REG_BASE + 0x454)
#define APU_ACE_CMD_Q_STATUS_6			(APU_ARE_REG_BASE + 0x458)
#define APU_ACE_CMD_Q_STATUS_7			(APU_ARE_REG_BASE + 0x45c)
#define APU_ACE_SW_DONE_FLAG_ALL		(APU_ARE_REG_BASE + 0x480)
#define APU_ACE_SW_ORDER_FLAG			(APU_ARE_REG_BASE + 0x484)
#define APU_ACE_SW_OCCUPIED_FLAG		(APU_ARE_REG_BASE + 0x488)
#define APU_ACE_SW_CMD_Q_0_DONE_FLAG		(APU_ARE_REG_BASE + 0x490)
#define APU_ACE_SW_CMD_Q_1_DONE_FLAG		(APU_ARE_REG_BASE + 0x494)
#define APU_ACE_SW_CMD_Q_2_DONE_FLAG		(APU_ARE_REG_BASE + 0x498)
#define APU_ACE_SW_CMD_Q_3_DONE_FLAG		(APU_ARE_REG_BASE + 0x49c)
#define APU_ACE_SW_CMD_Q_4_DONE_FLAG		(APU_ARE_REG_BASE + 0x4a0)
#define APU_ACE_SW_CMD_Q_5_DONE_FLAG		(APU_ARE_REG_BASE + 0x4a4)
#define APU_ACE_SW_CMD_Q_6_DONE_FLAG		(APU_ARE_REG_BASE + 0x4a8)
#define APU_ACE_SW_CMD_Q_7_DONE_FLAG		(APU_ARE_REG_BASE + 0x4ac)
#define APU_ACE_HW_JOB_BITMAP_0			(APU_ARE_REG_BASE + 0x4d0)
#define APU_ACE_HW_JOB_BITMAP_4			(APU_ARE_REG_BASE + 0x4d4)
#define APU_ACE_HW_JOB_BITMAP_8			(APU_ARE_REG_BASE + 0x4d8)
#define APU_ACE_HW_JOB_BITMAP_12		(APU_ARE_REG_BASE + 0x4dc)
#define APU_ACE_ABN_IRQ_FLAG_CE			(APU_ARE_REG_BASE + 0x4f0)
#define APU_ACE_ABN_IRQ_MASK_CE			(APU_ARE_REG_BASE + 0x4f8)
#define APU_ACE_ABN_IRQ_FLAG_ACE_SW		(APU_ARE_REG_BASE + 0x500)
#define APU_ACE_ABN_IRQ_FLAG_USER		(APU_ARE_REG_BASE + 0x504)
#define APU_ACE_ABN_IRQ_MASK_ACE_SW		(APU_ARE_REG_BASE + 0x508)
#define APU_ACE_ABN_IRQ_MASK_USER		(APU_ARE_REG_BASE + 0x50c)
#define APU_ACE_CE0_TASK_ING			(APU_ARE_REG_BASE + 0x510)
#define APU_ACE_CE1_TASK_ING			(APU_ARE_REG_BASE + 0x514)
#define APU_ACE_CE2_TASK_ING			(APU_ARE_REG_BASE + 0x518)
#define APU_ACE_CE3_TASK_ING			(APU_ARE_REG_BASE + 0x51c)
#define APU_ACE_CE0_TASK_ING_USER		(APU_ARE_REG_BASE + 0x520)
#define APU_ACE_CE1_TASK_ING_USER		(APU_ARE_REG_BASE + 0x524)
#define APU_ACE_CE2_TASK_ING_USER		(APU_ARE_REG_BASE + 0x528)
#define APU_ACE_CE3_TASK_ING_USER		(APU_ARE_REG_BASE + 0x52c)
#define APU_ACE_CE_CTRL_STATUS_0		(APU_ARE_REG_BASE + 0x530)
#define APU_ACE_MIRRORED_TIMESTAMP_0		(APU_ARE_REG_BASE + 0x538)
#define APU_ACE_MIRRORED_TIMESTAMP_1		(APU_ARE_REG_BASE + 0x53c)
#define APU_ACE_APB_MST_OUT_STATUS		(APU_ARE_REG_BASE + 0x540)
#define APU_ACE_APB_MST_OUT_STATUS_ERR		(APU_ARE_REG_BASE + 0x544)
#define APU_ACE_APB_MST_IN_STATUS		(APU_ARE_REG_BASE + 0x548)
#define APU_ACE_APB_MST_IN_STATUS_ERR		(APU_ARE_REG_BASE + 0x54C)
#define APU_ACE_HW_PEND_FLAG_0			(APU_ARE_REG_BASE + 0x550)
#define APU_ACE_HW_OCCUPIED_FLAG_0		(APU_ARE_REG_BASE + 0x558)
#define APU_ACE_HW_JOB_0_USER			(APU_ARE_REG_BASE + 0x560)
#define APU_ACE_HW_JOB_1_USER			(APU_ARE_REG_BASE + 0x564)
#define APU_ACE_HW_JOB_2_USER			(APU_ARE_REG_BASE + 0x568)
#define APU_ACE_HW_JOB_3_USER			(APU_ARE_REG_BASE + 0x56c)
#define APU_ACE_HW_JOB_4_USER			(APU_ARE_REG_BASE + 0x570)
#define APU_ACE_HW_JOB_5_USER			(APU_ARE_REG_BASE + 0x574)
#define APU_ACE_HW_JOB_6_USER			(APU_ARE_REG_BASE + 0x578)
#define APU_ACE_HW_JOB_7_USER			(APU_ARE_REG_BASE + 0x57c)
#define APU_ACE_HW_JOB_8_USER			(APU_ARE_REG_BASE + 0x580)
#define APU_ACE_HW_JOB_9_USER			(APU_ARE_REG_BASE + 0x584)
#define APU_ACE_HW_JOB_10_USER			(APU_ARE_REG_BASE + 0x588)
#define APU_ACE_HW_JOB_11_USER			(APU_ARE_REG_BASE + 0x58c)
#define APU_ACE_HW_JOB_12_USER			(APU_ARE_REG_BASE + 0x590)
#define APU_ACE_HW_JOB_13_USER			(APU_ARE_REG_BASE + 0x594)
#define APU_ACE_HW_JOB_14_USER			(APU_ARE_REG_BASE + 0x598)
#define APU_ACE_HW_JOB_15_USER			(APU_ARE_REG_BASE + 0x59c)
#define APU_ACE_JOB_TIEMOUT_CE0			(APU_ARE_REG_BASE + 0x5b0)
#define APU_ACE_JOB_TIEMOUT_CE1			(APU_ARE_REG_BASE + 0x5b4)
#define APU_ACE_JOB_TIEMOUT_CE2			(APU_ARE_REG_BASE + 0x5b8)
#define APU_ACE_JOB_TIEMOUT_CE3			(APU_ARE_REG_BASE + 0x5bc)
#define APU_ACE_SW_CMD_QUE_DIS			(APU_ARE_REG_BASE + 0x5d0)
#define APU_ACE_HW_FLAG_DIS			(APU_ARE_REG_BASE + 0x5d4)
#define APU_ACE_SW_CMD_QUE_CLR			(APU_ARE_REG_BASE + 0x5d8)
#define APU_ACE_HW_FLAG_CLR			(APU_ARE_REG_BASE + 0x5dc)
#define APU_ACE_SRAM_ENTRY_SEL			(APU_ARE_REG_BASE + 0x5e0)
#define APU_ACE_SRAM_ENTRY_RD			(APU_ARE_REG_BASE + 0x5e4)
#define APU_ACE_APB_MST_OUT_PADDR		(APU_ARE_REG_BASE + 0x5e8)
#define APU_ACE_APB_MST_IN_PADDR		(APU_ARE_REG_BASE + 0x5ec)
#define APU_ACE_IO_DEBUG			(APU_ARE_REG_BASE + 0x5f0)
#define APU_CE0_ABORT				(APU_ARE_REG_BASE + 0x610)
#define APU_CE0_IF_PC				(APU_ARE_REG_BASE + 0x620)
#define APU_CE0_IF_STATUS			(APU_ARE_REG_BASE + 0x624)
#define APU_CE0_RUN_STATUS			(APU_ARE_REG_BASE + 0x628)
#define APU_CE0_RUN_PC				(APU_ARE_REG_BASE + 0x62c)
#define APU_CE0_RUN_INSTR			(APU_ARE_REG_BASE + 0x630)
#define APU_CE0_RUN_INSTR_63_32			(APU_ARE_REG_BASE + 0x634)
#define APU_CE0_R0				(APU_ARE_REG_BASE + 0x640)
#define APU_CE0_R1				(APU_ARE_REG_BASE + 0x644)
#define APU_CE0_R2				(APU_ARE_REG_BASE + 0x648)
#define APU_CE0_R3				(APU_ARE_REG_BASE + 0x64c)
#define APU_CE0_R4				(APU_ARE_REG_BASE + 0x650)
#define APU_CE0_R5				(APU_ARE_REG_BASE + 0x654)
#define APU_CE0_R6				(APU_ARE_REG_BASE + 0x658)
#define APU_CE0_R7				(APU_ARE_REG_BASE + 0x65c)
#define APU_CE0_BAPB				(APU_ARE_REG_BASE + 0x668)
#define APU_CE0_BAXI				(APU_ARE_REG_BASE + 0x66c)
#define APU_CE0_SP				(APU_ARE_REG_BASE + 0x674)
#define APU_CE0_RA				(APU_ARE_REG_BASE + 0x678)
#define APU_CE0_TIMEOUT_INSTR			(APU_ARE_REG_BASE + 0x680)
#define APU_CE0_TIMEOUT_PC			(APU_ARE_REG_BASE + 0x684)
#define APU_CE0_INVLD_INSTR			(APU_ARE_REG_BASE + 0x688)
#define APU_CE0_INVLD_PC			(APU_ARE_REG_BASE + 0x68c)
#define APU_CE0_GO_NEXT				(APU_ARE_REG_BASE + 0x6a0)
#define APU_CE0_STEP				(APU_ARE_REG_BASE + 0x6a4)
#define APU_CE0_BREAKPOINT			(APU_ARE_REG_BASE + 0x6a8)
#define APU_CE0_OVERFLOW			(APU_ARE_REG_BASE + 0x6b0)
#define APU_CE1_ABORT				(APU_ARE_REG_BASE + 0x710)
#define APU_CE1_IF_PC				(APU_ARE_REG_BASE + 0x720)
#define APU_CE1_IF_STATUS			(APU_ARE_REG_BASE + 0x724)
#define APU_CE1_RUN_STATUS			(APU_ARE_REG_BASE + 0x728)
#define APU_CE1_RUN_PC				(APU_ARE_REG_BASE + 0x72c)
#define APU_CE1_RUN_INSTR			(APU_ARE_REG_BASE + 0x730)
#define APU_CE1_RUN_INSTR_63_32			(APU_ARE_REG_BASE + 0x734)
#define APU_CE1_R0				(APU_ARE_REG_BASE + 0x740)
#define APU_CE1_R1				(APU_ARE_REG_BASE + 0x744)
#define APU_CE1_R2				(APU_ARE_REG_BASE + 0x748)
#define APU_CE1_R3				(APU_ARE_REG_BASE + 0x74c)
#define APU_CE1_R4				(APU_ARE_REG_BASE + 0x750)
#define APU_CE1_R5				(APU_ARE_REG_BASE + 0x754)
#define APU_CE1_R6				(APU_ARE_REG_BASE + 0x758)
#define APU_CE1_R7				(APU_ARE_REG_BASE + 0x75c)
#define APU_CE1_BAPB				(APU_ARE_REG_BASE + 0x768)
#define APU_CE1_BAXI				(APU_ARE_REG_BASE + 0x76c)
#define APU_CE1_SP				(APU_ARE_REG_BASE + 0x774)
#define APU_CE1_RA				(APU_ARE_REG_BASE + 0x778)
#define APU_CE1_TIMEOUT_INSTR			(APU_ARE_REG_BASE + 0x780)
#define APU_CE1_TIMEOUT_PC			(APU_ARE_REG_BASE + 0x784)
#define APU_CE1_INVLD_INSTR			(APU_ARE_REG_BASE + 0x788)
#define APU_CE1_INVLD_PC			(APU_ARE_REG_BASE + 0x78c)
#define APU_CE1_GO_NEXT				(APU_ARE_REG_BASE + 0x7a0)
#define APU_CE1_STEP				(APU_ARE_REG_BASE + 0x7a4)
#define APU_CE1_BREAKPOINT			(APU_ARE_REG_BASE + 0x7a8)
#define APU_CE1_OVERFLOW			(APU_ARE_REG_BASE + 0x7b0)
#define APU_CE2_ABORT				(APU_ARE_REG_BASE + 0x810)
#define APU_CE2_IF_PC				(APU_ARE_REG_BASE + 0x820)
#define APU_CE2_IF_STATUS			(APU_ARE_REG_BASE + 0x824)
#define APU_CE2_RUN_STATUS			(APU_ARE_REG_BASE + 0x828)
#define APU_CE2_RUN_PC				(APU_ARE_REG_BASE + 0x82c)
#define APU_CE2_RUN_INSTR			(APU_ARE_REG_BASE + 0x830)
#define APU_CE2_RUN_INSTR_63_32			(APU_ARE_REG_BASE + 0x834)
#define APU_CE2_R0				(APU_ARE_REG_BASE + 0x840)
#define APU_CE2_R1				(APU_ARE_REG_BASE + 0x844)
#define APU_CE2_R2				(APU_ARE_REG_BASE + 0x848)
#define APU_CE2_R3				(APU_ARE_REG_BASE + 0x84c)
#define APU_CE2_R4				(APU_ARE_REG_BASE + 0x850)
#define APU_CE2_R5				(APU_ARE_REG_BASE + 0x854)
#define APU_CE2_R6				(APU_ARE_REG_BASE + 0x858)
#define APU_CE2_R7				(APU_ARE_REG_BASE + 0x85c)
#define APU_CE2_BAPB				(APU_ARE_REG_BASE + 0x868)
#define APU_CE2_BAXI				(APU_ARE_REG_BASE + 0x86c)
#define APU_CE2_SP				(APU_ARE_REG_BASE + 0x874)
#define APU_CE2_RA				(APU_ARE_REG_BASE + 0x878)
#define APU_CE2_TIMEOUT_INSTR			(APU_ARE_REG_BASE + 0x880)
#define APU_CE2_TIMEOUT_PC			(APU_ARE_REG_BASE + 0x884)
#define APU_CE2_INVLD_INSTR			(APU_ARE_REG_BASE + 0x888)
#define APU_CE2_INVLD_PC			(APU_ARE_REG_BASE + 0x88c)
#define APU_CE2_GO_NEXT				(APU_ARE_REG_BASE + 0x8a0)
#define APU_CE2_STEP				(APU_ARE_REG_BASE + 0x8a4)
#define APU_CE2_BREAKPOINT			(APU_ARE_REG_BASE + 0x8a8)
#define APU_CE2_OVERFLOW			(APU_ARE_REG_BASE + 0x8b0)
#define APU_CE3_ABORT				(APU_ARE_REG_BASE + 0x910)
#define APU_CE3_IF_PC				(APU_ARE_REG_BASE + 0x920)
#define APU_CE3_IF_STATUS			(APU_ARE_REG_BASE + 0x924)
#define APU_CE3_RUN_STATUS			(APU_ARE_REG_BASE + 0x928)
#define APU_CE3_RUN_PC				(APU_ARE_REG_BASE + 0x92c)
#define APU_CE3_RUN_INSTR			(APU_ARE_REG_BASE + 0x930)
#define APU_CE3_RUN_INSTR_63_32			(APU_ARE_REG_BASE + 0x934)
#define APU_CE3_R0				(APU_ARE_REG_BASE + 0x940)
#define APU_CE3_R1				(APU_ARE_REG_BASE + 0x944)
#define APU_CE3_R2				(APU_ARE_REG_BASE + 0x948)
#define APU_CE3_R3				(APU_ARE_REG_BASE + 0x94c)
#define APU_CE3_R4				(APU_ARE_REG_BASE + 0x950)
#define APU_CE3_R5				(APU_ARE_REG_BASE + 0x954)
#define APU_CE3_R6				(APU_ARE_REG_BASE + 0x958)
#define APU_CE3_R7				(APU_ARE_REG_BASE + 0x95c)
#define APU_CE3_BAPB				(APU_ARE_REG_BASE + 0x968)
#define APU_CE3_BAXI				(APU_ARE_REG_BASE + 0x96c)
#define APU_CE3_SP				(APU_ARE_REG_BASE + 0x974)
#define APU_CE3_RA				(APU_ARE_REG_BASE + 0x978)
#define APU_CE3_TIMEOUT_INSTR			(APU_ARE_REG_BASE + 0x980)
#define APU_CE3_TIMEOUT_PC			(APU_ARE_REG_BASE + 0x984)
#define APU_CE3_INVLD_INSTR			(APU_ARE_REG_BASE + 0x988)
#define APU_CE3_INVLD_PC			(APU_ARE_REG_BASE + 0x98c)
#define APU_CE3_GO_NEXT				(APU_ARE_REG_BASE + 0x9a0)
#define APU_CE3_STEP				(APU_ARE_REG_BASE + 0x9a4)
#define APU_CE3_BREAKPOINT			(APU_ARE_REG_BASE + 0x9a8)
#define APU_CE3_OVERFLOW			(APU_ARE_REG_BASE + 0x9b0)

#define APU_CE_REG_SZ				(0x1000)
#define APU_CE_DEBUG_APB_SZ			(0x1000)

#define CE_REG_CTRL_BASE			(APU_ARE_REG_BASE + 0x0)
#define CE_REG_DEBUG_CTRL_BASE			(APU_ARE_DEBUG_APB_BASE + 0x0)

#define CE_REG_DUMP_MAGIC_NUM			(0xA5A5A5A5)

#define CE_SMC_OP_TABLE \
	ENTRY(SMC_OP_APU_CE_NULL,                    0x0)\
	ENTRY(SMC_OP_APU_ACE_ABN_IRQ_FLAG_CE,        APU_ACE_ABN_IRQ_FLAG_CE)\
	ENTRY(SMC_OP_APU_ACE_ABN_IRQ_FLAG_ACE_SW,    APU_ACE_ABN_IRQ_FLAG_ACE_SW)\
	ENTRY(SMC_OP_APU_ACE_ABN_IRQ_FLAG_USER,      APU_ACE_ABN_IRQ_FLAG_USER)\
	ENTRY(SMC_OP_APU_ACE_CE0_TASK_ING,           APU_ACE_CE0_TASK_ING)\
	ENTRY(SMC_OP_APU_ACE_CE1_TASK_ING,           APU_ACE_CE1_TASK_ING)\
	ENTRY(SMC_OP_APU_ACE_CE2_TASK_ING,           APU_ACE_CE2_TASK_ING)\
	ENTRY(SMC_OP_APU_ACE_CE3_TASK_ING,           APU_ACE_CE3_TASK_ING)\
	ENTRY(SMC_OP_APU_CE0_RUN_INSTR,              APU_CE0_RUN_INSTR)\
	ENTRY(SMC_OP_APU_CE1_RUN_INSTR,              APU_CE1_RUN_INSTR)\
	ENTRY(SMC_OP_APU_CE2_RUN_INSTR,              APU_CE2_RUN_INSTR)\
	ENTRY(SMC_OP_APU_CE3_RUN_INSTR,              APU_CE3_RUN_INSTR)\
	ENTRY(SMC_OP_APU_CE0_TIMEOUT_INSTR,          APU_CE0_TIMEOUT_INSTR)\
	ENTRY(SMC_OP_APU_CE1_TIMEOUT_INSTR,          APU_CE1_TIMEOUT_INSTR)\
	ENTRY(SMC_OP_APU_CE2_TIMEOUT_INSTR,          APU_CE2_TIMEOUT_INSTR)\
	ENTRY(SMC_OP_APU_CE3_TIMEOUT_INSTR,          APU_CE3_TIMEOUT_INSTR)\
	ENTRY(SMC_OP_APU_ACE_APB_MST_OUT_STATUS_ERR, APU_ACE_APB_MST_OUT_STATUS_ERR)\
	ENTRY(SMC_OP_APU_ACE_APB_MST_IN_STATUS_ERR,  APU_ACE_APB_MST_IN_STATUS_ERR)\
	ENTRY(SMC_OP_APU_CE0_RUN_PC,                 APU_CE0_RUN_PC)\
	ENTRY(SMC_OP_APU_CE1_RUN_PC,                 APU_CE1_RUN_PC)\
	ENTRY(SMC_OP_APU_CE2_RUN_PC,                 APU_CE2_RUN_PC)\
	ENTRY(SMC_OP_APU_CE3_RUN_PC,                 APU_CE3_RUN_PC)\
	ENTRY(SMC_OP_APU_ACE_CMD_Q_STATUS_0,         APU_ACE_CMD_Q_STATUS_0)\
	ENTRY(SMC_OP_APU_ACE_CMD_Q_STATUS_1,         APU_ACE_CMD_Q_STATUS_1)\
	ENTRY(SMC_OP_APU_ACE_CMD_Q_STATUS_2,         APU_ACE_CMD_Q_STATUS_2)\
	ENTRY(SMC_OP_APU_ACE_CMD_Q_STATUS_3,         APU_ACE_CMD_Q_STATUS_3)\
	ENTRY(SMC_OP_APU_ACE_CMD_Q_STATUS_4,         APU_ACE_CMD_Q_STATUS_4)\
	ENTRY(SMC_OP_APU_ACE_CMD_Q_STATUS_5,         APU_ACE_CMD_Q_STATUS_5)\
	ENTRY(SMC_OP_APU_ACE_CMD_Q_STATUS_6,         APU_ACE_CMD_Q_STATUS_6)\
	ENTRY(SMC_OP_APU_ACE_CMD_Q_STATUS_7,         APU_ACE_CMD_Q_STATUS_7)\
	ENTRY(SMC_OP_APU_CE0_STEP,                   APU_CE0_STEP)\
	ENTRY(SMC_OP_APU_CE1_STEP,                   APU_CE1_STEP)\
	ENTRY(SMC_OP_APU_CE2_STEP,                   APU_CE2_STEP)\
	ENTRY(SMC_OP_APU_CE3_STEP,                   APU_CE3_STEP)

#ifdef CONFIG_MTK_APUSYS_CE_PWR_INFRA_DUMP_SUPPORT
#define CE_DUMP_TABLE \
	ENTRY((APU_ARE_DEBUG_APB_BASE + 0x0400),              0x5B4)\
	ENTRY((APU_ARE_DEBUG_APB_BASE + 0x0E00),              0x020)\
	ENTRY((APU_ARE_DEBUG_APB_BASE + 0x0000),              0x1FC)\
	ENTRY((APU_RPCTOP_DEBUG_APB_BASE + 0x0044),           0x004)\
	ENTRY((APU_RPCTOP_LITE_ACX0_DEBUG_APB_BASE + 0x0014), 0x004)\
	ENTRY((APU_RPCTOP_LITE_ACX0_DEBUG_APB_BASE + 0x0044), 0x004)\
	ENTRY((APU_RPCTOP_LITE_ACX1_DEBUG_APB_BASE + 0x0014), 0x004)\
	ENTRY((APU_RPCTOP_LITE_ACX1_DEBUG_APB_BASE + 0x0044), 0x004)\
	ENTRY((APU_RPCTOP_LITE_NCX_DEBUG_APB_BASE + 0x0014),  0x004)\
	ENTRY((APU_RPCTOP_LITE_NCX_DEBUG_APB_BASE + 0x0044),  0x004)
#else
#define CE_DUMP_TABLE \
	ENTRY((APU_ARE_DEBUG_APB_BASE + 0x0400),              0x5B4)\
	ENTRY((APU_ARE_DEBUG_APB_BASE + 0x0E00),              0x020)\
	ENTRY((APU_ARE_DEBUG_APB_BASE + 0x0000),              0x1FC)
#endif /* CONFIG_MTK_APUSYS_CE_PWR_INFRA_DUMP_SUPPORT */

#endif /* APUSYS_CE_H */
