/* SPDX-License-Identifier: BSD-3-Clause */
/*
 * Copyright (c) 2024 MediaTek Inc.
 */

#ifndef PLL_H
#define PLL_H
#include <stdint.h>
#include <platform_def.h>

/* INFRA_AO_bcrm Register */
#define VDNR_DCM_INFRA_PAR_BUS_CTRL_0				(INFRA_AO_BCRM_BASE + 0x0038)

/* INFRA_INFRACFG_AO_REG Register */
#define INFRA_BUS_DCM_CTRL					(INFRACFG_AO_BASE + 0x0070)

/* MCUSYS_CONFIG_REG Register */
#define CPU_PLLDIV_0_CFG0             (MCUCFG_BASE + 0xA2A0)
#define CPU_PLLDIV_1_CFG0             (MCUCFG_BASE + 0xA2A4)
#define BUS_PLLDIV_CFG0               (MCUCFG_BASE + 0xA2E0)

/* PERI_AO_BCRM Register */
#define VDNR_DCM_PERI_PAR_BUS_CTRL_0				(PERI_AO_BCRM_BASE + 0x0020)

/* VCORE_CKGEN Register */
#define CLK_CFG_UPDATE						(TOPCKGEN_BASE + 0x0004)
#define CLK_CFG_UPDATE1						(TOPCKGEN_BASE + 0x0008)
#define CLK_CFG_UPDATE2						(TOPCKGEN_BASE + 0x000C)
#define CLK_CFG_0_SET						(TOPCKGEN_BASE + 0x0014)
#define CLK_CFG_0_CLR						(TOPCKGEN_BASE + 0x0018)
#define CLK_CFG_1_SET						(TOPCKGEN_BASE + 0x0024)
#define CLK_CFG_1_CLR						(TOPCKGEN_BASE + 0x0028)
#define CLK_CFG_2_SET						(TOPCKGEN_BASE + 0x0034)
#define CLK_CFG_2_CLR						(TOPCKGEN_BASE + 0x0038)
#define CLK_CFG_3_SET						(TOPCKGEN_BASE + 0x0044)
#define CLK_CFG_3_CLR						(TOPCKGEN_BASE + 0x0048)
#define CLK_CFG_4_SET						(TOPCKGEN_BASE + 0x0054)
#define CLK_CFG_4_CLR						(TOPCKGEN_BASE + 0x0058)
#define CLK_CFG_5_SET						(TOPCKGEN_BASE + 0x0064)
#define CLK_CFG_5_CLR						(TOPCKGEN_BASE + 0x0068)
#define CLK_CFG_6_SET						(TOPCKGEN_BASE + 0x0074)
#define CLK_CFG_6_CLR						(TOPCKGEN_BASE + 0x0078)
#define CLK_CFG_7_SET						(TOPCKGEN_BASE + 0x0084)
#define CLK_CFG_7_CLR						(TOPCKGEN_BASE + 0x0088)
#define CLK_CFG_8_SET						(TOPCKGEN_BASE + 0x0094)
#define CLK_CFG_8_CLR						(TOPCKGEN_BASE + 0x0098)
#define CLK_CFG_9_SET						(TOPCKGEN_BASE + 0x00A4)
#define CLK_CFG_9_CLR						(TOPCKGEN_BASE + 0x00A8)
#define CLK_CFG_10_SET						(TOPCKGEN_BASE + 0x00B4)
#define CLK_CFG_10_CLR						(TOPCKGEN_BASE + 0x00B8)
#define CLK_CFG_11_SET						(TOPCKGEN_BASE + 0x00C4)
#define CLK_CFG_11_CLR						(TOPCKGEN_BASE + 0x00C8)
#define CLK_CFG_12_SET						(TOPCKGEN_BASE + 0x00D4)
#define CLK_CFG_12_CLR						(TOPCKGEN_BASE + 0x00D8)
#define CLK_CFG_13_SET						(TOPCKGEN_BASE + 0x00E4)
#define CLK_CFG_13_CLR						(TOPCKGEN_BASE + 0x00E8)
#define CLK_CFG_14_SET						(TOPCKGEN_BASE + 0x00F4)
#define CLK_CFG_14_CLR						(TOPCKGEN_BASE + 0x00F8)
#define CLK_CFG_15_SET						(TOPCKGEN_BASE + 0x0104)
#define CLK_CFG_15_CLR						(TOPCKGEN_BASE + 0x0108)
#define CLK_CFG_16_SET						(TOPCKGEN_BASE + 0x0114)
#define CLK_CFG_16_CLR						(TOPCKGEN_BASE + 0x0118)
#define CLK_MISC_CFG_0						(TOPCKGEN_BASE + 0x0140)
#define CLK_MEM_DFS_CFG						(TOPCKGEN_BASE + 0x0160)
#define CLK_DBG_CFG						(TOPCKGEN_BASE + 0x017C)
#define CLK_CFG_17_SET						(TOPCKGEN_BASE + 0x0184)
#define CLK_CFG_17_CLR						(TOPCKGEN_BASE + 0x0188)
#define CLK_CFG_18_SET						(TOPCKGEN_BASE + 0x0194)
#define CLK_CFG_18_CLR						(TOPCKGEN_BASE + 0x0198)
#define CLK_SCP_CFG_0						(TOPCKGEN_BASE + 0x0200)
#define CLK26CALI_0						(TOPCKGEN_BASE + 0x0220)
#define CLK26CALI_1						(TOPCKGEN_BASE + 0x0224)
#define CLK_CFG_19_SET						(TOPCKGEN_BASE + 0x0244)
#define CLK_CFG_19_CLR						(TOPCKGEN_BASE + 0x0248)

/* VLP_CKGEN Register */
#define VLP_CLK_CFG_UPDATE					(VLP_CK_BASE + 0x0004)
#define VLP_CLK_CFG_0_SET					(VLP_CK_BASE + 0x000C)
#define VLP_CLK_CFG_0_CLR					(VLP_CK_BASE + 0x0010)
#define VLP_CLK_CFG_1_SET					(VLP_CK_BASE + 0x0018)
#define VLP_CLK_CFG_1_CLR					(VLP_CK_BASE + 0x001C)
#define VLP_CLK_CFG_2_SET					(VLP_CK_BASE + 0x0024)
#define VLP_CLK_CFG_2_CLR					(VLP_CK_BASE + 0x0028)
#define VLP_CLK_CFG_3_SET					(VLP_CK_BASE + 0x0030)
#define VLP_CLK_CFG_3_CLR					(VLP_CK_BASE + 0x0034)
#define VLP_CLK_CFG_4_SET					(VLP_CK_BASE + 0x003C)
#define VLP_CLK_CFG_4_CLR					(VLP_CK_BASE + 0x0040)
#define VLP_CLK_CFG_5_SET					(VLP_CK_BASE + 0x0048)
#define VLP_CLK_CFG_5_CLR					(VLP_CK_BASE + 0x004C)
#define VLP_FQMTR_CON0						(VLP_CK_BASE + 0x0230)
#define VLP_FQMTR_CON1						(VLP_CK_BASE + 0x0234)

/* TOPCKGEN Register */
#define TOPCKGEN_CLK_MISC_CFG_3					(TOPCKGEN_BASE + 0x0510)
#define TOPCKGEN_CLK_MISC_CFG_3_SET				(TOPCKGEN_BASE + 0x0514)
#define TOPCKGEN_CLK_MISC_CFG_3_CLR				(TOPCKGEN_BASE + 0x0518)

/* INFRACFG_AO Register */
#define INFRACFG_AO_MODULE_CG_0					(INFRACFG_AO_BASE + 0x0090)
#define INFRACFG_AO_MODULE_CG_0_SET				(INFRACFG_AO_BASE + 0x0080)
#define INFRACFG_AO_MODULE_CG_0_CLR				(INFRACFG_AO_BASE + 0x0084)
#define INFRACFG_AO_MODULE_CG_1					(INFRACFG_AO_BASE + 0x0094)
#define INFRACFG_AO_MODULE_CG_1_SET				(INFRACFG_AO_BASE + 0x0088)
#define INFRACFG_AO_MODULE_CG_1_CLR				(INFRACFG_AO_BASE + 0x008C)
#define INFRACFG_AO_MODULE_CG_2					(INFRACFG_AO_BASE + 0x00AC)
#define INFRACFG_AO_MODULE_CG_2_SET				(INFRACFG_AO_BASE + 0x00A4)
#define INFRACFG_AO_MODULE_CG_2_CLR				(INFRACFG_AO_BASE + 0x00A8)
#define INFRACFG_AO_MODULE_CG_3					(INFRACFG_AO_BASE + 0x00C8)
#define INFRACFG_AO_MODULE_CG_3_SET				(INFRACFG_AO_BASE + 0x00C0)
#define INFRACFG_AO_MODULE_CG_3_CLR				(INFRACFG_AO_BASE + 0x00C4)

/* INFRACFG_AO Register */
#define INFRACFG_AO_MMSYS_PROTECT_EN_STA_0	(INFRACFG_AO_BASE + 0x0C10)
#define INFRACFG_AO_MMSYS_PROTECT_EN_STA_0_SET	(INFRACFG_AO_BASE + 0x0C14)
#define INFRACFG_AO_MMSYS_PROTECT_EN_STA_0_CLR	(INFRACFG_AO_BASE + 0x0C18)
#define INFRACFG_AO_MMSYS_PROTECT_RDY_STA_0	(INFRACFG_AO_BASE + 0x0C1C)
#define INFRACFG_AO_MMSYS_PROTECT_EN_STA_1	(INFRACFG_AO_BASE + 0x0C20)
#define INFRACFG_AO_MMSYS_PROTECT_EN_STA_1_SET	(INFRACFG_AO_BASE + 0x0C24)
#define INFRACFG_AO_MMSYS_PROTECT_EN_STA_1_CLR	(INFRACFG_AO_BASE + 0x0C28)
#define INFRACFG_AO_MMSYS_PROTECT_RDY_STA_1	(INFRACFG_AO_BASE + 0x0C2C)
#define INFRACFG_AO_INFRASYS_PROTECT_EN_STA_0	(INFRACFG_AO_BASE + 0x0C40)
#define INFRACFG_AO_INFRASYS_PROTECT_EN_STA_0_SET	(INFRACFG_AO_BASE + 0x0C44)
#define INFRACFG_AO_INFRASYS_PROTECT_EN_STA_0_CLR	(INFRACFG_AO_BASE + 0x0C48)
#define INFRACFG_AO_INFRASYS_PROTECT_RDY_STA_0	(INFRACFG_AO_BASE + 0x0C4C)
#define INFRACFG_AO_INFRASYS_PROTECT_EN_STA_1	(INFRACFG_AO_BASE + 0x0C50)
#define INFRACFG_AO_INFRASYS_PROTECT_EN_STA_1_SET	(INFRACFG_AO_BASE + 0x0C54)
#define INFRACFG_AO_INFRASYS_PROTECT_EN_STA_1_CLR	(INFRACFG_AO_BASE + 0x0C58)
#define INFRACFG_AO_INFRASYS_PROTECT_RDY_STA_1	(INFRACFG_AO_BASE + 0x0C5C)
#define INFRACFG_AO_EMISYS_PROTECT_EN_STA_0	(INFRACFG_AO_BASE + 0x0C60)
#define INFRACFG_AO_EMISYS_PROTECT_EN_STA_0_SET	(INFRACFG_AO_BASE + 0x0C64)
#define INFRACFG_AO_EMISYS_PROTECT_EN_STA_0_CLR	(INFRACFG_AO_BASE + 0x0C68)
#define INFRACFG_AO_EMISYS_PROTECT_RDY_STA_0	(INFRACFG_AO_BASE + 0x0C6C)
#define INFRACFG_AO_PERISYS_PROTECT_EN_STA_0	(INFRACFG_AO_BASE + 0x0C80)
#define INFRACFG_AO_PERISYS_PROTECT_EN_STA_0_SET	(INFRACFG_AO_BASE + 0x0C84)
#define INFRACFG_AO_PERISYS_PROTECT_EN_STA_0_CLR	(INFRACFG_AO_BASE + 0x0C88)
#define INFRACFG_AO_PERISYS_PROTECT_RDY_STA_0	(INFRACFG_AO_BASE + 0x0C8C)
#define INFRACFG_AO_MCU_CONNSYS_PROTECT_EN_STA_0	(INFRACFG_AO_BASE + 0x0C90)
#define INFRACFG_AO_MCU_CONNSYS_PROTECT_EN_STA_0_SET (INFRACFG_AO_BASE + 0x0C94)
#define INFRACFG_AO_MCU_CONNSYS_PROTECT_EN_STA_0_CLR (INFRACFG_AO_BASE + 0x0C98)
#define INFRACFG_AO_MCU_CONNSYS_PROTECT_RDY_STA_0	 (INFRACFG_AO_BASE + 0x0C9C)
#define INFRACFG_AO_MD_MFGSYS_PROTECT_EN_STA_0	(INFRACFG_AO_BASE + 0x0CA0)
#define INFRACFG_AO_MD_MFGSYS_PROTECT_EN_STA_0_SET (INFRACFG_AO_BASE + 0x0CA4)
#define INFRACFG_AO_MD_MFGSYS_PROTECT_EN_STA_0_CLR (INFRACFG_AO_BASE + 0x0CA8)
#define INFRACFG_AO_MD_MFGSYS_PROTECT_RDY_STA_0	(INFRACFG_AO_BASE + 0x0CAC)

/* APMIXEDSYS Register */
#define APLL1_TUNER_CON0					(APMIXED_BASE + 0x0040)
#define APLL2_TUNER_CON0					(APMIXED_BASE + 0x0044)
#define PLLEN_ALL_SET						(APMIXED_BASE + 0x0074)
#define PLLEN_ALL_CLR						(APMIXED_BASE + 0x0078)
#define PLL_DIV_RSTB_ALL_SET					(APMIXED_BASE + 0x0084)
#define ARMPLL_LL_CON0						(APMIXED_BASE + 0x0204)
#define ARMPLL_LL_CON1						(APMIXED_BASE + 0x0208)
#define ARMPLL_BL_CON0						(APMIXED_BASE + 0x0214)
#define ARMPLL_BL_CON1						(APMIXED_BASE + 0x0218)
#define CCIPLL_CON0						(APMIXED_BASE + 0x0224)
#define CCIPLL_CON1						(APMIXED_BASE + 0x0228)
#define MAINPLL_CON0						(APMIXED_BASE + 0x0304)
#define MAINPLL_CON1						(APMIXED_BASE + 0x0308)
#define UNIVPLL_CON0						(APMIXED_BASE + 0x0314)
#define UNIVPLL_CON1						(APMIXED_BASE + 0x0318)
#define MMPLL_CON0						(APMIXED_BASE + 0x0324)
#define MMPLL_CON1						(APMIXED_BASE + 0x0328)
#define EMIPLL_CON0						(APMIXED_BASE + 0x0334)
#define EMIPLL_CON1						(APMIXED_BASE + 0x0338)
#define APLL1_CON0						(APMIXED_BASE + 0x0404)
#define APLL1_CON1						(APMIXED_BASE + 0x0408)
#define APLL1_CON2						(APMIXED_BASE + 0x040C)
#define APLL2_CON0						(APMIXED_BASE + 0x0418)
#define APLL2_CON1						(APMIXED_BASE + 0x041C)
#define APLL2_CON2						(APMIXED_BASE + 0x0420)
#define TVDPLL1_CON0						(APMIXED_BASE + 0x042C)
#define TVDPLL1_CON1						(APMIXED_BASE + 0x0430)
#define TVDPLL2_CON0						(APMIXED_BASE + 0x043C)
#define TVDPLL2_CON1						(APMIXED_BASE + 0x0440)
#define MFGPLL_CON0						(APMIXED_BASE + 0x0504)
#define MFGPLL_CON1						(APMIXED_BASE + 0x0508)
#define ETHPLL_CON0						(APMIXED_BASE + 0x0514)
#define ETHPLL_CON1						(APMIXED_BASE + 0x0518)
#define MSDCPLL_CON0						(APMIXED_BASE + 0x0524)
#define MSDCPLL_CON1						(APMIXED_BASE + 0x0528)
#define UFSPLL_CON0						(APMIXED_BASE + 0x0534)
#define UFSPLL_CON1						(APMIXED_BASE + 0x0538)
#define APUPLL_CON0						(APMIXED_BASE + 0x0604)
#define APUPLL_CON1						(APMIXED_BASE + 0x0608)
#define APUPLL2_CON0						(APMIXED_BASE + 0x0614)
#define APUPLL2_CON1						(APMIXED_BASE + 0x0618)
#define AP_CLKSQ_CON0						(APMIXED_BASE + 0x0700)

/* EMICFG_AO_MEM Register */
#define EMICFG_AO_MEM_GALS_SLP_PROT_EN				(EMICFG_AO_MEM_BASE + 0x0080)
#define EMICFG_AO_MEM_GALS_SLP_PROT_EN_SET			(EMICFG_AO_MEM_BASE + 0x0084)
#define EMICFG_AO_MEM_GALS_SLP_PROT_EN_CLR			(EMICFG_AO_MEM_BASE + 0x0088)
#define EMICFG_AO_MEM_GALS_SLP_PROT_RDY				(EMICFG_AO_MEM_BASE + 0x008C)

/* PERICFG_AO Register */
#define PERICFG_AO_PERI_CG_0					(PERICFG_AO_BASE + 0x0010)
#define PERICFG_AO_PERI_CG_0_SET				(PERICFG_AO_BASE + 0x0024)
#define PERICFG_AO_PERI_CG_0_CLR				(PERICFG_AO_BASE + 0x0028)
#define PERICFG_AO_PERI_CG_1					(PERICFG_AO_BASE + 0x0014)
#define PERICFG_AO_PERI_CG_1_SET				(PERICFG_AO_BASE + 0x002C)
#define PERICFG_AO_PERI_CG_1_CLR				(PERICFG_AO_BASE + 0x0030)
#define PERICFG_AO_PERI_CG_2					(PERICFG_AO_BASE + 0x0018)
#define PERICFG_AO_PERI_CG_2_SET				(PERICFG_AO_BASE + 0x0034)
#define PERICFG_AO_PERI_CG_2_CLR				(PERICFG_AO_BASE + 0x0038)
#define PERICFG_AO_CLOCK_CON					(PERICFG_AO_BASE + 0x0020)

/* AFE Register */
#define AUDIO_AUDIO_TOP_0					(AUDIO_BASE + 0x0000)
#define AUDIO_AUDIO_TOP_4					(AUDIO_BASE + 0x0010)
#define AUDIO_AUDIO_TOP_1					(AUDIO_BASE + 0x0004)
#define AUDIO_AUDIO_TOP_2					(AUDIO_BASE + 0x0008)
#define AUDIO_AUDIO_TOP_3					(AUDIO_BASE + 0x000C)

/* UFSCFG_AO_REG Register */
#define UFSCFG_AO_REG_UFS_AO_CG_0				(UFS0_AO_CFG_BASE + 0x0004)
#define UFSCFG_AO_REG_UFS_AO_CG_0_SET				(UFS0_AO_CFG_BASE + 0x0008)
#define UFSCFG_AO_REG_UFS_AO_CG_0_CLR				(UFS0_AO_CFG_BASE + 0x000C)

/* UFSCFG_PDN_REG Register */
#define UFSCFG_PDN_REG_UFS_PDN_CG_0				(UFS0_PDN_CFG_BASE + 0x0004)
#define UFSCFG_PDN_REG_UFS_PDN_CG_0_SET				(UFS0_PDN_CFG_BASE + 0x0008)
#define UFSCFG_PDN_REG_UFS_PDN_CG_0_CLR				(UFS0_PDN_CFG_BASE + 0x000C)

/* IMP_IIC_WRAP_WS Register */
#define IMP_IIC_WRAP_WS_AP_CLOCK_CG				(IMP_IIC_WRAP_WS_BASE + 0x0E00)
#define IMP_IIC_WRAP_WS_AP_CLOCK_CG_SET				(IMP_IIC_WRAP_WS_BASE + 0x0E08)
#define IMP_IIC_WRAP_WS_AP_CLOCK_CG_CLR				(IMP_IIC_WRAP_WS_BASE + 0x0E04)

/* IMP_IIC_WRAP_E Register */
#define IMP_IIC_WRAP_E_AP_CLOCK_CG				(IMP_IIC_WRAP_E_BASE + 0x0E00)
#define IMP_IIC_WRAP_E_AP_CLOCK_CG_SET				(IMP_IIC_WRAP_E_BASE + 0x0E08)
#define IMP_IIC_WRAP_E_AP_CLOCK_CG_CLR				(IMP_IIC_WRAP_E_BASE + 0x0E04)

/* IMP_IIC_WRAP_S Register */
#define IMP_IIC_WRAP_S_AP_CLOCK_CG				(IMP_IIC_WRAP_S_BASE + 0x0E00)
#define IMP_IIC_WRAP_S_AP_CLOCK_CG_SET				(IMP_IIC_WRAP_S_BASE + 0x0E08)
#define IMP_IIC_WRAP_S_AP_CLOCK_CG_CLR				(IMP_IIC_WRAP_S_BASE + 0x0E04)

/* IMP_IIC_WRAP_EN Register */
#define IMP_IIC_WRAP_EN_AP_CLOCK_CG				(IMP_IIC_WRAP_EN_BASE + 0x0E00)
#define IMP_IIC_WRAP_EN_AP_CLOCK_CG_SET				(IMP_IIC_WRAP_EN_BASE + 0x0E08)
#define IMP_IIC_WRAP_EN_AP_CLOCK_CG_CLR				(IMP_IIC_WRAP_EN_BASE + 0x0E04)

/* MFG Register */
#define MFG_MFG_CG_CON						(MFGCFG_BASE + 0x0000)
#define MFG_MFG_CG_CON_SET					(MFGCFG_BASE + 0x0004)
#define MFG_MFG_CG_CON_CLR					(MFGCFG_BASE + 0x0008)

/* DISPSYS_CONFIG Register */
#define MMSYS_CONFIG_MMSYS_CG_0					(MMSYS_CONFIG_BASE + 0x0100)
#define MMSYS_CONFIG_MMSYS_CG_0_SET				(MMSYS_CONFIG_BASE + 0x0104)
#define MMSYS_CONFIG_MMSYS_CG_0_CLR				(MMSYS_CONFIG_BASE + 0x0108)
#define MMSYS_CONFIG_MMSYS_CG_1					(MMSYS_CONFIG_BASE + 0x0110)
#define MMSYS_CONFIG_MMSYS_CG_1_SET				(MMSYS_CONFIG_BASE + 0x0114)
#define MMSYS_CONFIG_MMSYS_CG_1_CLR				(MMSYS_CONFIG_BASE + 0x0118)

/* IMGSYS1 Register */
#define IMGSYS1_IMG_CG						(IMGSYS1_BASE + 0x0000)
#define IMGSYS1_IMG_CG_SET					(IMGSYS1_BASE + 0x0004)
#define IMGSYS1_IMG_CG_CLR					(IMGSYS1_BASE + 0x0008)

/* IMGSYS2 Register */
#define IMGSYS2_IMG_CG						(IMGSYS2_BASE + 0x0000)
#define IMGSYS2_IMG_CG_SET					(IMGSYS2_BASE + 0x0004)
#define IMGSYS2_IMG_CG_CLR					(IMGSYS2_BASE + 0x0008)

/* VDEC_CORE Register */
#define VDEC_CORE_VDEC_CKEN					(VDEC_CORE_BASE + 0x0000)
#define VDEC_CORE_VDEC_CKEN_SET					(VDEC_CORE_BASE + 0x0000)
#define VDEC_CORE_VDEC_CKEN_CLR					(VDEC_CORE_BASE + 0x0004)
#define VDEC_CORE_LARB_CKEN_CON					(VDEC_CORE_BASE + 0x0008)
#define VDEC_CORE_LARB_CKEN_CON_SET				(VDEC_CORE_BASE + 0x0008)
#define VDEC_CORE_LARB_CKEN_CON_CLR				(VDEC_CORE_BASE + 0x000C)

/* VENC_GCON Register */
#define VENC_GCON_VENCSYS_CG					(VENC_GCON_BASE + 0x0000)
#define VENC_GCON_VENCSYS_CG_SET				(VENC_GCON_BASE + 0x0004)
#define VENC_GCON_VENCSYS_CG_CLR				(VENC_GCON_BASE + 0x0008)

/* SPM Register */
#define CONN_PWR_CON						(SPM_BASE + 0x0E04)
#define UFS0_PWR_CON						(SPM_BASE + 0x0E10)
#define UFS0_PHY_PWR_CON					(SPM_BASE + 0x0E14)
#define AUDIO_PWR_CON						(SPM_BASE + 0x0E18)
#define ADSP_TOP_PWR_CON					(SPM_BASE + 0x0E1C)
#define ADSP_INFRA_PWR_CON					(SPM_BASE + 0x0E20)
#define ADSP_AO_PWR_CON						(SPM_BASE + 0x0E24)
#define ISP_IMG1_PWR_CON					(SPM_BASE + 0x0E28)
#define ISP_IMG2_PWR_CON					(SPM_BASE + 0x0E2C)
#define ISP_IPE_PWR_CON						(SPM_BASE + 0x0E30)
#define VDE0_PWR_CON						(SPM_BASE + 0x0E38)
#define VEN0_PWR_CON						(SPM_BASE + 0x0E40)
#define CAM_MAIN_PWR_CON					(SPM_BASE + 0x0E48)
#define CAM_SUBA_PWR_CON					(SPM_BASE + 0x0E50)
#define CAM_SUBB_PWR_CON					(SPM_BASE + 0x0E54)
#define MDP0_PWR_CON						(SPM_BASE + 0x0E68)
#define DIS0_PWR_CON						(SPM_BASE + 0x0E70)
#define MM_INFRA_PWR_CON					(SPM_BASE + 0x0E78)
#define DP_TX_PWR_CON						(SPM_BASE + 0x0E80)
#define SCP_PERI_PWR_CON					(SPM_BASE + 0x0E88)
#define CSI_RX_PWR_CON						(SPM_BASE + 0x0E9C)
#define SSUSB_PWR_CON						(SPM_BASE + 0x0EA8)
#define MFG0_PWR_CON						(SPM_BASE + 0x0EB4)
#define MFG1_PWR_CON						(SPM_BASE + 0x0EB8)
#define MFG2_PWR_CON						(SPM_BASE + 0x0EBC)
#define MFG3_PWR_CON						(SPM_BASE + 0x0EC0)
#define PWR_STATUS						(SPM_BASE + 0x0F40)
#define PWR_STATUS_2ND						(SPM_BASE + 0x0F44)
#define EDP_TX_PWR_CON						(SPM_BASE + 0x0F70)
#define PCIE_PWR_CON						(SPM_BASE + 0x0F74)
#define PCIE_PHY_PWR_CON					(SPM_BASE + 0x0F78)

/* VLPCFG_REG_BUS Register */
#define VLPCFG_REG_BUS_VLP_TOPAXI_PROTECTEN			(VLPCFG_REG_BUS_BASE + 0x0210)
#define VLPCFG_REG_BUS_VLP_TOPAXI_PROTECTEN_SET			(VLPCFG_REG_BUS_BASE + 0x0214)
#define VLPCFG_REG_BUS_VLP_TOPAXI_PROTECTEN_CLR			(VLPCFG_REG_BUS_BASE + 0x0218)
#define VLPCFG_REG_BUS_VLP_TOPAXI_PROTECTEN_STA1		(VLPCFG_REG_BUS_BASE + 0x0220)

/* VLP_CKSYS Register */
#define VLP_CK_VLP_CLK_CFG_30					(VLP_CK_BASE + 0x01F0)
#define VLP_CK_VLP_CLK_CFG_30_SET				(VLP_CK_BASE + 0x01F4)
#define VLP_CK_VLP_CLK_CFG_30_CLR				(VLP_CK_BASE + 0x01F8)

/* VLPCFG_REG Register */
#define VLPCFG_REG_VLP_TEST_CK_CTRL				(VLPCFG_REG_BASE + 0x0004)

/* SCP_IIC Register */
#define SCP_IIC_CCU_CLOCK_CG					(SCP_IIC_BASE + 0x0E10)
#define SCP_IIC_CCU_CLOCK_CG_SET				(SCP_IIC_BASE + 0x0E18)
#define SCP_IIC_CCU_CLOCK_CG_CLR				(SCP_IIC_BASE + 0x0E14)

/* SCP Register */
#define SCP_AP_SPI_CG						(SCP_BASE + 0x0154)
#define SCP_AP_SPI_CG_SET					(SCP_BASE + 0x0154)
#define SCP_AP_SPI_CG_CLR					(SCP_BASE + 0x0158)

/* VADSYS Register */
#define VAD_VADSYS_CK_EN					(VAD_BASE + 0x0000)
#define VAD_VOW_AUDIODSP_SW_CG					(VAD_BASE + 0x0180)

/* CAMSYS_MAIN Register */
#define CAMSYS_MAIN_CAMSYS_CG					(CAMSYS_MAIN_BASE + 0x0000)
#define CAMSYS_MAIN_CAMSYS_CG_SET				(CAMSYS_MAIN_BASE + 0x0004)
#define CAMSYS_MAIN_CAMSYS_CG_CLR				(CAMSYS_MAIN_BASE + 0x0008)

/* CAMSYS_RAWA Register */
#define CAMSYS_RAWA_CAMSYS_CG					(CAMSYS_RAWA_BASE + 0x0000)
#define CAMSYS_RAWA_CAMSYS_CG_SET				(CAMSYS_RAWA_BASE + 0x0004)
#define CAMSYS_RAWA_CAMSYS_CG_CLR				(CAMSYS_RAWA_BASE + 0x0008)

/* CAMSYS_RAWB Register */
#define CAMSYS_RAWB_CAMSYS_CG					(CAMSYS_RAWB_BASE + 0x0000)
#define CAMSYS_RAWB_CAMSYS_CG_SET				(CAMSYS_RAWB_BASE + 0x0004)
#define CAMSYS_RAWB_CAMSYS_CG_CLR				(CAMSYS_RAWB_BASE + 0x0008)

/* IPESYS Register */
#define IPE_IMG_CG						(IPE_BASE + 0x0000)
#define IPE_IMG_CG_SET						(IPE_BASE + 0x0004)
#define IPE_IMG_CG_CLR						(IPE_BASE + 0x0008)

/* VLPCFG_AO_REG Register */
#define VLPCFG_AO_REG_DEBUGTOP_VLPAO_CTRL			(VLPCFG_AO_REG_BASE + 0x0800)

/* DVFSRC_TOP Register */
#define DVFSRC_TOP_DVFSRC_BASIC_CONTROL				(DVFSRC_TOP_BASE + 0x0000)

/* MMINFRA_CONFIG Register */
#define MMINFRA_CONFIG_MMINFRA_CG_0				(MMINFRA_CONFIG_BASE + 0x0100)
#define MMINFRA_CONFIG_MMINFRA_CG_0_SET				(MMINFRA_CONFIG_BASE + 0x0104)
#define MMINFRA_CONFIG_MMINFRA_CG_0_CLR				(MMINFRA_CONFIG_BASE + 0x0108)
#define MMINFRA_CONFIG_MMINFRA_CG_1				(MMINFRA_CONFIG_BASE + 0x0110)
#define MMINFRA_CONFIG_MMINFRA_CG_1_SET				(MMINFRA_CONFIG_BASE + 0x0114)
#define MMINFRA_CONFIG_MMINFRA_CG_1_CLR				(MMINFRA_CONFIG_BASE + 0x0118)

/* GCE_D Register */
#define GCE_GCE_CTL_INT0					(GCE_BASE + 0x00F0)

/* GCE_M Register */
#define MDP_GCE_GCE_CTL_INT0					(MDP_GCE_BASE + 0x00F0)

/* MDPSYS_CONFIG Register */
#define MDPSYS_CONFIG_MDPSYS_CG_0				(MDPSYS_CONFIG_BASE + 0x0100)
#define MDPSYS_CONFIG_MDPSYS_CG_0_SET				(MDPSYS_CONFIG_BASE + 0x0104)
#define MDPSYS_CONFIG_MDPSYS_CG_0_CLR				(MDPSYS_CONFIG_BASE + 0x0108)
#define MDPSYS_CONFIG_MDPSYS_CG_1				(MDPSYS_CONFIG_BASE + 0x0110)
#define MDPSYS_CONFIG_MDPSYS_CG_1_SET				(MDPSYS_CONFIG_BASE + 0x0114)
#define MDPSYS_CONFIG_MDPSYS_CG_1_CLR				(MDPSYS_CONFIG_BASE + 0x0118)

/* DBGAO Register */
#define DBGAO_ATB						(DBGAO_BASE + 0x0070)

/* DEM Register */
#define DEM_DBGBUSCLK_EN					(DEM_BASE + 0x002C)
#define DEM_DBGSYSCLK_EN					(DEM_BASE + 0x0030)
#define DEM_ATB							(DEM_BASE + 0x0070)

/* Fmeter Type */
enum fmeter_type {
	APLL1_CTRL,
	APLL2_CTRL,
	ARMPLL_BL_CTRL,
	ARMPLL_LL_CTRL,
	CCIPLL_CTRL,
	MAINPLL_CTRL,
	MMPLL_CTRL,
	MSDCPLL_CTRL,
	UFSPLL_CTRL,
	UNIVPLL_CTRL,
	EMIPLL_CTRL,
	TVDPLL1_CTRL,
	TVDPLL2_CTRL,
	MFGPLL_CTRL,
	ETHPLL_CTRL,
	APUPLL_CTRL,
	APUPLL2_CTRL,
	VLP_CKSYS_TOP_CTRL,
};

/* PLL set rate list */
enum PLL_LIST {
	ARMPLL_LL_RATE = 0,
	ARMPLL_BL_RATE,
	CCIPLL_RATE,
	PLL_RATE_NUM,
};

#define ARMPLL_BL_ID			6
#define ARMPLL_LL_ID			8
#define CCIPLL_ID				10

/*
 * CLKMGR EXTERN FUNCTIONS
 */
extern unsigned int mt_get_abist_freq(unsigned int ID);
extern unsigned int mt_get_vlpck_freq(unsigned int ID);
extern unsigned int mt_get_cpu_freq(unsigned int ID);
extern void mt_set_topck_default(void);
extern void set_pll_rate(enum PLL_LIST pll_id, uint32_t khz);
extern void mt_pll_init(void);
extern void set_armpll_ll_rate(uint32_t khz);
extern void set_armpll_bl_rate(uint32_t khz);
extern void set_ccipll_rate(uint32_t khz);
extern void mt_dump_cpu_freq(void);
#endif	/* PLL_H */
