/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein is
 * confidential and proprietary to MediaTek Inc. and/or its licensors. Without
 * the prior written permission of MediaTek inc. and/or its licensors, any
 * reproduction, modification, use or disclosure of MediaTek Software, and
 * information contained herein, in whole or in part, shall be strictly
 * prohibited.
 *
 * MediaTek Inc. (C) 2010. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER
 * ON AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR
 * NONINFRINGEMENT. NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH
 * RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,
 * INCORPORATED IN, OR SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES
 * TO LOOK ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO.
 * RECEIVER EXPRESSLY ACKNOWLEDGES THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO
 * OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES CONTAINED IN MEDIATEK
 * SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE
 * RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S
 * ENTIRE AND CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE
 * RELEASED HEREUNDER WILL BE, AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE
 * MEDIATEK SOFTWARE AT ISSUE, OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE
 * CHARGE PAID BY RECEIVER TO MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek
 * Software") have been modified by MediaTek Inc. All revisions are subject to
 * any receiver's applicable license agreements with MediaTek Inc.
 */

#ifndef _SPM_MTCMOS_
#define _SPM_MTCMOS_

#define STA_POWER_DOWN  0
#define STA_POWER_ON    1

enum power_domain_id {
	MT8195_POWER_DOMAIN_PCIE_MAC_P0 = 0,
	MT8195_POWER_DOMAIN_PCIE_MAC_P1,
	MT8195_POWER_DOMAIN_PCIE_PHY,
	MT8195_POWER_DOMAIN_SSUSB_PCIE_PHY,
	MT8195_POWER_DOMAIN_CSI_RX_TOP,
	MT8195_POWER_DOMAIN_ETHER,
	MT8195_POWER_DOMAIN_ADSP,
	MT8195_POWER_DOMAIN_AUDIO,
	MT8195_POWER_DOMAIN_AUDIO_ASRC,
	MT8195_POWER_DOMAIN_NNA,
	MT8195_POWER_DOMAIN_NNA0,
	MT8195_POWER_DOMAIN_NNA1,
	MT8195_POWER_DOMAIN_MFG0,
	MT8195_POWER_DOMAIN_MFG1,
	MT8195_POWER_DOMAIN_MFG2,
	MT8195_POWER_DOMAIN_MFG3,
	MT8195_POWER_DOMAIN_MFG4,
	MT8195_POWER_DOMAIN_MFG5,
	MT8195_POWER_DOMAIN_MFG6,
	MT8195_POWER_DOMAIN_VPPSYS0,
	MT8195_POWER_DOMAIN_VDOSYS0,
	MT8195_POWER_DOMAIN_VPPSYS1,
	MT8195_POWER_DOMAIN_VDOSYS1,
	MT8195_POWER_DOMAIN_DP_TX,
	MT8195_POWER_DOMAIN_EPD_TX,
	MT8195_POWER_DOMAIN_HDMI_TX,
	MT8195_POWER_DOMAIN_HDMI_RX,
	MT8195_POWER_DOMAIN_WPESYS,
	MT8195_POWER_DOMAIN_VDEC0,
	MT8195_POWER_DOMAIN_VDEC1,
	MT8195_POWER_DOMAIN_VDEC2,
	MT8195_POWER_DOMAIN_VENC,
	MT8195_POWER_DOMAIN_VENC_CORE1,
	MT8195_POWER_DOMAIN_IMG,
	MT8195_POWER_DOMAIN_DIP,
	MT8195_POWER_DOMAIN_IPE,
	MT8195_POWER_DOMAIN_CAM,
	MT8195_POWER_DOMAIN_CAM_RAWA,
	MT8195_POWER_DOMAIN_CAM_RAWB,
	MT8195_POWER_DOMAIN_CAM_MRAW,
	MT8195_POWER_DOMAIN_NR,
};

void spm_mtcmos_on(enum power_domain_id ID);
void spm_mtcmos_off(enum power_domain_id ID);
void spm_mtcmos_on_all(void);

#endif
