#
# Copyright (c) 2022, MediaTek Inc. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

# call add_defined_option to evaluate MTK defined value
$(eval $(call add_defined_option,MTK_SIP_KERNEL_BOOT_ENABLE))
$(eval $(call add_defined_option,PLAT_EXTRA_RODATA_INCLUDES))
$(eval $(call add_defined_option,MTK_EXTRA_LINKERFILE))
$(eval $(call add_defined_option,MTK_BL31_AS_BL2))
$(eval $(call add_defined_option,MTK_BL33_IS_64BIT))
$(eval $(call add_defined_option,PLAT_XLAT_TABLES_DYNAMIC))
$(eval $(call add_defined_option,MTK_ADAPTED))
$(eval $(call add_defined_option,MTK_PUBEVENT_ENABLE))
$(eval $(call add_defined_option,MTK_SOC))
$(eval $(call add_defined_option,UART_CLOCK))
$(eval $(call add_defined_option,UART_BAUDRATE))
$(eval $(call add_defined_option,CONFIG_MTK_APUSYS_RV))
$(eval $(call add_defined_option,CONFIG_MTK_APUSYS_RV_SECURE_BOOT))
$(eval $(call add_defined_option,CONFIG_MTK_APUSYS_RV_SECURE_BOOT_MT8XXX))
$(eval $(call add_defined_option,CONFIG_MTK_APUSYS_CE_SUPPORT))
$(eval $(call add_defined_option,CONFIG_MTK_APUSYS_AOV_TCM_DUMP_SUPPORT))
$(eval $(call add_defined_option,CONFIG_MTK_APUSYS_RV_COREDUMP_WA_SUPPORT))
$(eval $(call add_defined_option,CONFIG_MTK_APUSYS_CE_PWR_INFRA_DUMP_SUPPORT))
$(eval $(call add_defined_option,CONFIG_MTK_APUSYS_LOGTOP_SUPPORT))
$(eval $(call add_defined_option,CONFIG_MTK_APUSYS_RV_IOMMU_HW_SEM_SUPPORT))
$(eval $(call add_defined_option,CONFIG_MTK_APUSYS_RV_APUMMU_SUPPORT))
$(eval $(call add_defined_option,CONFIG_MTK_APUSYS_RV_CUSTOM_MBOX_MPU))
$(eval $(call add_defined_option,CONFIG_MTK_APUSYS_REG_DUMP))
$(eval $(call add_defined_option,CONFIG_MTK_APUSYS_SEC_CTRL))
$(eval $(call add_defined_option,CONFIG_MTK_APUSYS_PWR))
$(eval $(call add_defined_option,CONFIG_MTK_APUSYS_KERNEL_LOAD_IMAGE))
$(eval $(call add_defined_option,CONFIG_MTK_APUSYS_APPEND_IOMMU_PAGE_TBL))
$(eval $(call add_defined_option,CONFIG_MTK_APUSYS_SMPU))
$(eval $(call add_defined_option,CONFIG_MTK_APUSYS_COMMON))
$(eval $(call add_defined_option,CONFIG_MTK_MCUSYS))
$(eval $(call add_defined_option,CONFIG_MTK_PM_SUPPORT))
$(eval $(call add_defined_option,CONFIG_MTK_CPU_PM_SUPPORT))
$(eval $(call add_defined_option,CONFIG_MTK_SMP_EN))
$(eval $(call add_defined_option,CONFIG_MTK_CPU_SUSPEND_EN))
$(eval $(call add_defined_option,CONFIG_MTK_PM_ARCH))
$(eval $(call add_defined_option,CONFIG_MTK_CPU_PM_ARCH))
$(eval $(call add_defined_option,MTK_IOT_YOCTO))
$(eval $(call add_defined_option,PLAT_PARTITION_BLOCK_SIZE))
$(eval $(call add_defined_option,CONFIG_MTK_APUSYS_RV_SECURE_BOOT))
$(eval $(call add_defined_option,CONFIG_MTK_SUPPORT_SYSTEM_SUSPEND))
$(eval $(call add_defined_option,CONFIG_MTK_CIRQ_REMAIN))
$(eval $(call add_defined_option,CONFIG_MTK_DFD_SUPPORT))
