/*
 * Copyright (c) 2021, Mediatek Inc. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef APUSYS_SECURITY_CTRL_H
#define APUSYS_SECURITY_CTRL_H

#define DOMAIN_REMAP(D0_REMAP_DOMAIN, D1_REMAP_DOMAIN, \
					D2_REMAP_DOMAIN, D3_REMAP_DOMAIN, \
					D4_REMAP_DOMAIN, D5_REMAP_DOMAIN, \
					D6_REMAP_DOMAIN, D7_REMAP_DOMAIN, \
					D8_REMAP_DOMAIN, D9_REMAP_DOMAIN, \
					D10_REMAP_DOMAIN, D11_REMAP_DOMAIN, \
					D12_REMAP_DOMAIN, D13_REMAP_DOMAIN, \
					D14_REMAP_DOMAIN, D15_REMAP_DOMAIN) \
		{D0_REMAP_DOMAIN, D1_REMAP_DOMAIN, \
		D2_REMAP_DOMAIN, D3_REMAP_DOMAIN, \
		D4_REMAP_DOMAIN, D5_REMAP_DOMAIN, \
		D6_REMAP_DOMAIN, D7_REMAP_DOMAIN, \
		D8_REMAP_DOMAIN, D9_REMAP_DOMAIN, \
		D10_REMAP_DOMAIN, D11_REMAP_DOMAIN, \
		D12_REMAP_DOMAIN, D13_REMAP_DOMAIN, \
		D14_REMAP_DOMAIN, D15_REMAP_DOMAIN}

#endif
